version: '3.7'

services:
  binance-bot:
    container_name: binance-bot
    # image: chrisleekr/binance-trading-bot:latest
    image: clayton/binance-bot-bkh:latest
    networks:
      - internal
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./config/:/srv/config
    environment:
      # - BINANCE_MODE=test
      - BINANCE_MODE=live
      - BINANCE_JOBS_ALIVE_ENABLED=true
      - BINANCE_JOBS_TRAILING_TRADE_ENABLED=true

      #symbols
      - BINANCE_JOBS_TRAILING_TRADE_SYMBOLS=["AXSUSDT"]
      # - BINANCE_JOBS_TRAILING_TRADE_SYMBOLS=["AAVEUPUSDT","ETHUPUSDT","ADAUPUSDT","LTCUPUSDT","DOTUPUSDT","UNIUPUSDT","YFIUPUSDT","LINKUPUSDT"]
      # - BINANCE_JOBS_TRAILING_TRADE_SYMBOLS=["AAVEDOWNUSDT","ETHDOWNUSDT","ADADOWNUSDT","LTCDOWNUSDT","DOTDOWNUSDT","UNIDOWNUSDT","FILDOWNUSDT"]
      # - BINANCE_JOBS_TRAILING_TRADE_CANDLES_INTERVAL=15m
      # - BINANCE_JOBS_TRAILING_TRADE_CANDLES_LIMIT=30

      #buy
      # - BINANCE_JOBS_TRAILING_TRADE_BUY_TRIGGER_PERCENTAGE=1.04
      # - BINANCE_JOBS_TRAILING_TRADE_BUY_STOP_PERCENTAGE=1.04
      # - BINANCE_JOBS_TRAILING_TRADE_BUY_LIMIT_PERCENTAGE=1.041

      # #sell
      # - BINANCE_JOBS_TRAILING_TRADE_SELL_TRIGGER_PERCENTAGE=1.1
      # - BINANCE_JOBS_TRAILING_TRADE_SELL_STOP_PERCENTAGE=0.99
      # - BINANCE_JOBS_TRAILING_TRADE_SELL_LIMIT_PERCENTAGE=0.989

      #stoploss
      # - BINANCE_JOBS_TRAILING_TRADE_SELL_STOP_LOSS_ENABLED=true
      # - BINANCE_JOBS_TRAILING_TRADE_SELL_STOP_LOSS_MAX_LOSS_PERCENTAGE=0.85
      # - BINANCE_JOBS_TRAILING_TRADE_SELL_STOP_LOSS_DISABLE_BUY_MINUTES=60

      #ath
      # - BINANCE_JOBS_TRAILING_TRADE_BUY_ATH_RESTRICTION_ENABLE=true
      # - BINANCE_JOBS_TRAILING_TRADE_BUY_ATH_RESTRICTION_CANDLES_INTERVAL=30m
      # - BINANCE_JOBS_TRAILING_TRADE_BUY_ATH_RESTRICTION_CANDLES_LIMIT=4
      # - BINANCE_JOBS_TRAILING_TRADE_BUY_ATH_RESTRICTION_RESTRICTION_PERCENTAGE=0.9

      #redis settings
      - BINANCE_REDIS_HOST=binance-redis
      - BINANCE_REDIS_PORT=6379
      - BINANCE_REDIS_PASSWORD=secretp422

      #system settings
      - BINANCE_JOBS_TRAILING_TRADE_SYSTEM_REFRESH_ACCOUNT_INFO_PERIOD=10
      - BINANCE_JOBS_TRAILING_TRADE_SYSTEM_CHECK_ORDER_EXECUTE_PERIOD=10
      - BINANCE_AUTHENTICATION_ENABLED=false
      - BINANCE_AUTHENTICATION_PASSWORD=1234

    ports:
      - 8081:80
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  binance-redis:
    container_name: binance-redis
    image: redis
    sysctls:
      net.core.somaxconn: 1024
    networks:
      - internal
    restart: unless-stopped
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      redis-server /usr/local/etc/redis/redis.conf --requirepass secretp422

  binance-mongo:
    container_name: binance-mongo
    image: mongo
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - mongo_data:/data/db

networks:
  internal:
    driver: bridge
    # driver_opts:
    #     com.docker.network.driver.mtu: 1442

volumes:
  config:
  redis_data:
  mongo_data:
